MD_Baltimore:
  address: "VARCHAR(128)"
  block: "VARCHAR(5)"
  class: "VARCHAR(32)"
  date: "VARCHAR(12)"
  description: "VARCHAR(128)"
  district: "VARCHAR(16)"
  incident: "VARCHAR(32)"
  latitude: "FLOAT"
  longitude: "FLOAT"
  neighborhood: "VARCHAR(32)"
  time: "VARCHAR(5)"
  timestamp: "INT UNSIGNED"
  zipcode: "VARCHAR(5)"
  zone: "VARCHAR(32)"