CA_SanFrancisco_Fire:
  address: "VARCHAR(128)"
  agency: "VARCHAR(12)"
  beat: "VARCHAR(32)"
  block: "VARCHAR(4)"
  class: "VARCHAR(128)"
  date: "VARCHAR(12)"
  date_entry: "VARCHAR(12)"
  date_response: "VARCHAR(12)"
  date_transport: "VARCHAR(12)"
  date_arrival: "VARCHAR(12)"
  date_dispatch: "VARCHAR(12)"
  date_hospital: "VARCHAR(12)"
  date_closed: "VARCHAR(12)"
  description: "VARCHAR(128)"
  department: "VARCHAR(32)"
  district: "VARCHAR(2)"
  incident: "VARCHAR(8)"
  latitude: "FLOAT"
  longitude: "FLOAT"
  neighborhood: "VARCHAR(128)"
  priority: "VARCHAR(2)"
  time: "VARCHAR(5)"
  time_entry: "VARCHAR(5)"
  time_response: "VARCHAR(5)"
  time_transport: "VARCHAR(5)"
  time_arrival: "VARCHAR(5)"
  time_closed: "VARCHAR(5)"
  time_dispatch: "VARCHAR(5)"
  time_hospital: "VARCHAR(5)"
  timestamp: "INT UNSIGNED"
  timestamp_entry: "INT UNSIGNED"
  timestamp_response: "INT UNSIGNED"
  timestamp_transport: "INT UNSIGNED"
  timestamp_arrival: "INT UNSIGNED"
  timestamp_closed: "INT UNSIGNED"
  timestamp_dispatch: "INT UNSIGNED"
  timestamp_hospital: "INT UNSIGNED"
  zipcode: "VARCHAR(5)"