MA_Cambridge:
  classification: "VARCHAR(32)"
  description: "VARCHAR(128)"
  priority: "TINYINT" 
  address: "VARCHAR(128)"
  sector: "TINYINT" 
  date: "VARCHAR(12)"
  date_closed: "VARCHAR(12)"
  time: "VARCHAR(5)"
  time_closed: "VARCHAR(5)"
  timestamp: "INT UNSIGNED"
  timestamp_closed: "INT UNSIGNED"
  neighborhood: "VARCHAR(32)"
  area: "VARCHAR(5)"
  department: "VARCHAR(5)"