OH_Cincinnati:
  address: "VARCHAR(128)"
  agency: "VARCHAR(32)"
  beat: "VARCHAR(32)"
  classification: "VARCHAR(32)"
  date: "VARCHAR(12)"
  date_arrival: "VARCHAR(12)"
  date_closed: "VARCHAR(12)"
  date_dispatch: "VARCHAR(12)"
  description: "VARCHAR(128)"
  disposition: "VARCHAR(32)"
  district: "VARCHAR(16)"
  incident: "VARCHAR(32)"
  latitude: "FLOAT"
  longitude: "FLOAT"
  neighborhood: "VARCHAR(32)"
  priority: "TINYINT"
  time: "VARCHAR(5)"
  time_arrival: "VARCHAR(5)"
  time_closed: "VARCHAR(5)"
  time_dispatch: "VARCHAR(5)"
  timestamp: "INT UNSIGNED"
  timestamp_arrival: "INT UNSIGNED"
  timestamp_closed: "INT UNSIGNED"
  timestamp_dispatch: "INT UNSIGNED"