WA_Seattle:
  beat: "VARCHAR(2)"
  class: "VARCHAR(128)"
  class_end: "VARCHAR(128)"
  date: "VARCHAR(12)"
  date_arrival: "VARCHAR(12)"
  description: "VARCHAR(128)"
  incident: "VARCHAR(32)"
  priority: "TINYINT"
  sector: "VARCHAR(32)"
  time: "VARCHAR(5)"
  time_arrival: "VARCHAR(5)"
  timestamp: "INT UNSIGNED"
  timestamp_arrival: "INT UNSIGNED"
  type: "VARCHAR(32)"
  zone: "VARCHAR(32)"
