LA_NewOrleans:
  address: "VARCHAR(128)"
  beat: "VARCHAR(4)"
  classification: "VARCHAR(128)"
  date: "VARCHAR(12)"
  date_arrival: "VARCHAR(12)"
  date_closed: "VARCHAR(12)"
  date_dispatch: "VARCHAR(12)"
  description: "VARCHAR(128)"
  district: "VARCHAR(2)"
  incident: "VARCHAR(8)"
  latitude: "FLOAT"
  longitude: "FLOAT"
  priority: "VARCHAR(2)"
  source: "VARCHAR(2)"
  time: "VARCHAR(5)"
  time_arrival: "VARCHAR(5)"
  time_closed: "VARCHAR(5)"
  time_dispatch: "VARCHAR(5)"
  timestamp: "INT UNSIGNED"
  timestamp_arrival: "INT UNSIGNED"
  timestamp_dispatch: "INT UNSIGNED"
  timestamp_closed: "INT UNSIGNED"
  zipcode: "VARCHAR(5)"